
course_data = [
  {"name":"History of Western Art","dept":"Art","short_name":"ARTS 001"},
  {"name":"Fundamentals of Drawing","dept":"Art","short_name":"ARTS 011"},
  {"name":"Graphic Design and Color","dept":"Art","short_name":"ARTS 013"},
  {"name":"History of Western Art","dept":"Art","short_name":"ARTS 101"},
  {"name":"Fundamentals of Drawing","dept":"Art","short_name":"ARTS 111"},
  {"name":"Computer Graphics","dept":"Art","short_name":"ARTS 115"},
  {"name":"Digital Imaging","dept":"Art","short_name":"ARTS 117"},
  {"name":"Beginning Painting: Acrylics","dept":"Art","short_name":"ARTS 121"},
  {"name":"Intermediate Painting:Acrylics","dept":"Art","short_name":"ARTS 122"},
  {"name":"Advanced Painting: Acrylics","dept":"Art","short_name":"ARTS 123"},
  {"name":"Multimedia Printmaking","dept":"Art","short_name":"ARTS 132"},
  {"name":"Advanced Printmaking Workshop","dept":"Art","short_name":"ARTS 134"},
  {"name":"Beginning Ceramics","dept":"Art","short_name":"ARTS 141"},
  {"name":"Intermediate Ceramics","dept":"Art","short_name":"ARTS 142"},
  {"name":"Advanced Ceramics","dept":"Art","short_name":"ARTS 143"},
  {"name":"Beginning Jewelry and Metal","dept":"Art","short_name":"ARTS 181"},
  {"name":"Intermediate Jewelry and Metal","dept":"Art","short_name":"ARTS 182"},
  {"name":"Advanced Jewelry and Metal","dept":"Art","short_name":"ARTS 183"},
  {"name":"Drama Workshop:","dept":"Art","short_name":"DRAM 099"},
  {"name":"Drama Workshop","dept":"Art","short_name":"DRAM 099 1"},
  {"name":"Drama Workshop","dept":"Art","short_name":"DRAM 099 2"},
  {"name":"Principles of Biological Science","dept":"Biological Science","short_name":"BIOL 001A"},
  {"name":"Principles of Biological Science","dept":"Biological Science","short_name":"BIOL 001A"},
  {"name":"Principles of Biological Science Lab","dept":"Biological Science","short_name":"BIOL 001AL"},
  {"name":"Principles of Biological Science Lab","dept":"Biological Science","short_name":"BIOL 001AL"},
  {"name":"Principles of Biological Science","dept":"Biological Science","short_name":"BIOL 001B"},
  {"name":"Principles of Biological Science Lab","dept":"Biological Science","short_name":"BIOL 001BL"},
  {"name":"Human Physiology","dept":"Biological Science","short_name":"BIOL 011"},
  {"name":"Human Physiology Laboratory","dept":"Biological Science","short_name":"BIOL 011L"},
  {"name":"Human Biology","dept":"Biological Science","short_name":"BIOL 015"},
  {"name":"Human Biology","dept":"Biological Science","short_name":"BIOL 015"},
  {"name":"Human Anatomy","dept":"Biological Science","short_name":"BIOL 017"},
  {"name":"Human Anatomy Laboratory","dept":"Biological Science","short_name":"BIOL 017L"},
  {"name":"Human Anatomy Laboratory","dept":"Biological Science","short_name":"BIOL 017L"},
  {"name":"Allied Health Microbiology","dept":"Biological Science","short_name":"BIOL 020"},
  {"name":"Allied Health Microbiology Laboratory","dept":"Biological Science","short_name":"BIOL 020L"},
  {"name":"Medical Microbiology","dept":"Biological Science","short_name":"BIOL 145"},
  {"name":"Medical Microbiology Lab","dept":"Biological Science","short_name":"BIOL 145L"},
  {"name":"Physiological Chem","dept":"Biological Science","short_name":"BIOL 185"},
  {"name":"Physiological Chemistry Lab","dept":"Biological Science","short_name":"BIOL 185L"},
  {"name":"Biology Seminar","dept":"Biological Science","short_name":"BIOL 192W"},
  {"name":"Internship","dept":"Biological Science","short_name":"BIOL 196"},
  {"name":"Internship","dept":"Biological Science","short_name":"BIOL 196 1"},
  {"name":"Internship","dept":"Biological Science","short_name":"BIOL 196 2"},
  {"name":"Principles of Accounting","dept":"Business","short_name":"BSAD 012"},
  {"name":"Principles of Accounting","dept":"Business","short_name":"BSAD 012"},
  {"name":"Quantitative Analysis for Business and Economics","dept":"Business","short_name":"BSAD 020"},
  {"name":"Principles of Management","dept":"Business","short_name":"BSAD 030"},
  {"name":"Decision Analysis For Business","dept":"Business","short_name":"BSAD 105"},
  {"name":"Survey of Global Business","dept":"Business","short_name":"BSAD 113W"},
  {"name":"Global Business","dept":"Business","short_name":"BSAD 113W"},
  {"name":"Business Finance","dept":"Business","short_name":"BSAD 129"},
  {"name":"Business Management","dept":"Business","short_name":"BSAD 130"},
  {"name":"Organizational Behavior","dept":"Business","short_name":"BSAD 148W"},
  {"name":"Principles of Marketing","dept":"Business","short_name":"BSAD 160"},
  {"name":"Marketing Research","dept":"Business","short_name":"BSAD 165"},
  {"name":"Sports Marketing and Public Relations","dept":"Business","short_name":"BSAD 171"},
  {"name":"Strategic Management","dept":"Business","short_name":"BSAD 195W"},
  {"name":"Internship","dept":"Business","short_name":"BSAD 196"},
  {"name":"Internship","dept":"Business","short_name":"BSAD 196 1"},
  {"name":"Internship","dept":"Business","short_name":"BSAD 196 2"},
  {"name":"Academic Success Strategies","dept":"Career and Life Planning","short_name":"CALP 095"},
  {"name":"Leadership, Trans & Social Change I","dept":"Career and Life Planning","short_name":"CALP 191"},
  {"name":"Career Exploration: Internship","dept":"Career and Life Planning","short_name":"CALP 196"},
  {"name":"Career Exploration: Internship","dept":"Career and Life Planning","short_name":"CALP 196 1"},
  {"name":"Career Exploration: Internship","dept":"Career and Life Planning","short_name":"CALP 196 2"},
  {"name":"General Chemistry and Qualitative Analysis","dept":"Chemistry","short_name":"CHEM 001B"},
  {"name":"General Chemistry Discussion","dept":"Chemistry","short_name":"CHEM 001BDis"},
  {"name":"General Chemistry Lab","dept":"Chemistry","short_name":"CHEM 001BL"},
  {"name":"Introductory Chemistry for Health Science","dept":"Chemistry","short_name":"CHEM 007"},
  {"name":"Intro to Chemistry Laboratory","dept":"Chemistry","short_name":"CHEM 007L"},
  {"name":"Organic Chemistry II","dept":"Chemistry","short_name":"CHEM 019"},
  {"name":"Organic Chemistry II Lab","dept":"Chemistry","short_name":"CHEM 019L"},
  {"name":"Professional Writing","dept":"Communication","short_name":"COMM 108W"},
  {"name":"Essen Interpersonal Comm/Effect Speaking","dept":"Communications Studies","short_name":"COMM 001"},
  {"name":"Essen Interpersonal Comm/Effect Speaking","dept":"Communications Studies","short_name":"COMM 001"},
  {"name":"Essen Interpersonal Comm/Effect Speaking","dept":"Communications Studies","short_name":"COMM 001"},
  {"name":"Presentation Strategies","dept":"Communications Studies","short_name":"COMM 110"},
  {"name":"Mediation and Conflict Resolution","dept":"Communications Studies","short_name":"COMM 122"},
  {"name":"Internship","dept":"Communications Studies","short_name":"COMM 196"},
  {"name":"Internship","dept":"Communications Studies","short_name":"COMM 196 1"},
  {"name":"Internship","dept":"Communications Studies","short_name":"COMM 196 2"},
  {"name":"Spreadsheets","dept":"Computer Systems","short_name":"CSCI 010C"},
  {"name":"The Criminal Justice System","dept":"Criminology","short_name":"CRIM 120"},
  {"name":"Academic Internship","dept":"Criminology","short_name":"CRIM 196"},
  {"name":"Academic Internship","dept":"Criminology","short_name":"CRIM 196 1"},
  {"name":"Academic Internship","dept":"Criminology","short_name":"CRIM 196 2"},
  {"name":"Principles of Economics (Micro)","dept":"Economics","short_name":"ECON 002"},
  {"name":"Principles Of Economics (Micro)","dept":"Economics","short_name":"ECON 002"},
  {"name":"Statistical Methods","dept":"Economics","short_name":"ECON 015"},
  {"name":"Social Foundations in Education","dept":"Education","short_name":"EDUC 100"},
  {"name":"Educational Psychology","dept":"Education","short_name":"EDUC 101"},
  {"name":"Educating Students with Special Needs","dept":"Education","short_name":"EDUC 102A"},
  {"name":"Multicultural Education","dept":"Education","short_name":"EDUC 102B"},
  {"name":"Theories/Methods Second Language Acquisition","dept":"Education","short_name":"EDUC 103"},
  {"name":"Writing Workshop","dept":"English","short_name":"ENGL A"},
  {"name":"Critical Reading and Writing I","dept":"English","short_name":"ENGL 001A"},
  {"name":"Critical Reading and Writing II","dept":"English","short_name":"ENGL 001B"},
  {"name":"Critical Reading and Writing II","dept":"English","short_name":"ENGL 001B"},
  {"name":"Critical Reading and Writing II","dept":"English","short_name":"ENGL 001B"},
  {"name":"Critical Reading and Writing II","dept":"English","short_name":"ENGL 001B"},
  {"name":"Critical Reading and Writing II","dept":"English","short_name":"ENGL 001B"},
  {"name":"Critical Reading and Writing II","dept":"English","short_name":"ENGL 001B"},
  {"name":"Critical Reading and Writing II","dept":"English","short_name":"ENGL 001B"},
  {"name":"Critical Reading and Writing II","dept":"English","short_name":"ENGL 001B"},
  {"name":"Intensive Writing","dept":"English","short_name":"ENGL 018 1"},
  {"name":"Intensive Writing","dept":"English","short_name":"ENGL 018 2"},
  {"name":"Intensive Writing","dept":"English","short_name":"ENGL 018 3"},
  {"name":"Dramatic Literature","dept":"English","short_name":"ENGL 022W"},
  {"name":"Creative Writing","dept":"English","short_name":"ENGL 107W"},
  {"name":"Professional Writing","dept":"English","short_name":"ENGL 108W"},
  {"name":"Dramatic Literature","dept":"English","short_name":"ENGL 122 W"},
  {"name":"19th Century American Literature","dept":"English","short_name":"ENGL 130"},
  {"name":"Children's Literature","dept":"English","short_name":"ENGL 151"},
  {"name":"Intensive Writing","dept":"English as a Second Language","short_name":"ESLG 018 1"},
  {"name":"Intensive Writing","dept":"English as a Second Language","short_name":"ESLG 018 2"},
  {"name":"Intensive Writing","dept":"English as a Second Language","short_name":"ESLG 018 3"},
  {"name":"Academic Skills II","dept":"English as a Second Language","short_name":"ESLG 019"},
  {"name":"Crit Reading/Writing for Non-Native Speakers","dept":"English as a Second Language","short_name":"ESLG 024B"},
  {"name":"Techniques of Communicative Interaction","dept":"English as a Second Language","short_name":"ESLG 025"},
  {"name":"Elementary French II","dept":"French","short_name":"FREN 002"},
  {"name":"US History: Survey B","dept":"History","short_name":"HIST 017B"},
  {"name":"Contemporary Europe","dept":"History","short_name":"HIST 124"},
  {"name":"Latino/Hispanic Experience","dept":"History","short_name":"HIST 177"},
  {"name":"Internship","dept":"History","short_name":"HIST 196"},
  {"name":"Internship","dept":"History","short_name":"HIST 196 1"},
  {"name":"Internship","dept":"History","short_name":"HIST 196 2"},
  {"name":"History of the Middle East & North Africa","dept":"History","short_name":"HIST 197"},
  {"name":"The Premodern World","dept":"Integrative Studies Across Cultures","short_name":"ISAC 002"},
  {"name":"The Premodern World","dept":"Integrative Studies Across Cultures","short_name":"ISAC 002"},
  {"name":"The Contemporary World","dept":"Integrative Studies Across Cultures","short_name":"ISAC 004"},
  {"name":"The Contemporary World","dept":"Integrative Studies Across Cultures","short_name":"ISAC 004"},
  {"name":"The Ancient World","dept":"Integrative Studies Across Cultures","short_name":"ISAC 101"},
  {"name":"The Ancient World","dept":"Integrative Studies Across Cultures","short_name":"ISAC 101"},
  {"name":"The Premodern World","dept":"Integrative Studies Across Cultures","short_name":"ISAC 102"},
  {"name":"The Modern World","dept":"Integrative Studies Across Cultures","short_name":"ISAC 103"},
  {"name":"The Modern World","dept":"Integrative Studies Across Cultures","short_name":"ISAC 103"},
  {"name":"The Contemporary World","dept":"Integrative Studies Across Cultures","short_name":"ISAC 104"},
  {"name":"Senior Colloquium: \"Film Historical Injustices\"","dept":"Integrative Studies Across Cultures","short_name":"ISAC 195W"},
  {"name":"Senior Colloquium: \"Oakland\"","dept":"Integrative Studies Across Cultures","short_name":"ISAC 195W"},
  {"name":"Senior Colloquium: \"Spiritual Activism\"","dept":"Integrative Studies Across Cultures","short_name":"ISAC 195W"},
  {"name":"Senior Colloquium \"Protest\"","dept":"Integrative Studies Across Cultures","short_name":"ISAC 195W"},
  {"name":"Senior Colloquium: Memory","dept":"Integrative Studies Across Cultures","short_name":"ISAC 195W"},
  {"name":"Latin American Art and Music Experience","dept":"Latin American and Latino/a Studies","short_name":"LALS 115"},
  {"name":"Internship","dept":"Latin American and Latino/a Studies","short_name":"LALS 196"},
  {"name":"Special Topics: Travel Course to Oaxaca","dept":"Latin American and Latino/a Studies","short_name":"LALS 197"},
  {"name":"Internship","dept":"Liberal Studies","short_name":"CHDT 196 1"},
  {"name":"Internship","dept":"Liberal Studies","short_name":"CHDT 196 1"},
  {"name":"Introduction to Liberal Studies","dept":"Liberal Studies","short_name":"LBST 010"},
  {"name":"Internship","dept":"Liberal Studies","short_name":"LBST 196"},
  {"name":"Internship","dept":"Liberal Studies","short_name":"LBST 196 1"},
  {"name":"Internship","dept":"Liberal Studies","short_name":"LBST 196 2"},
  {"name":"Fundamentals of Language","dept":"Linguistics","short_name":"LING 145"},
  {"name":"Sociolinguistics","dept":"Linguistics","short_name":"LING 154"},
  {"name":"Math for Elementary School Teachers","dept":"Math","short_name":"MATH 151"},
  {"name":"Algebra 2 Workshop","dept":"Mathematics","short_name":"MATH A"},
  {"name":"Algebra 2 Workshop","dept":"Mathematics","short_name":"MATH A"},
  {"name":"Algebra 1 Workshop","dept":"Mathematics","short_name":"MATH C"},
  {"name":"Precalculus","dept":"Mathematics","short_name":"MATH 001"},
  {"name":"Calculus II","dept":"Mathematics","short_name":"MATH 012"},
  {"name":"Probability & Statistics","dept":"Mathematics","short_name":"MATH 060"},
  {"name":"World Music","dept":"Music","short_name":"MUSC 001B"},
  {"name":"Renaissance to Baroque Music: Musicianship and Theory","dept":"Music","short_name":"MUSC 013A"},
  {"name":"Renaissance to Baroque Music: History and Theory","dept":"Music","short_name":"MUSC 013B"},
  {"name":"Private Lessons","dept":"Music","short_name":"MUSC 016"},
  {"name":"Private Lessons/Second Instrument","dept":"Music","short_name":"MUSC 017"},
  {"name":"Piano Class","dept":"Music","short_name":"MUSC 020B"},
  {"name":"Voice Class","dept":"Music","short_name":"MUSC 022B"},
  {"name":"HNU Chorus","dept":"Music","short_name":"MUSC 060"},
  {"name":"HNU Chamber Singers","dept":"Music","short_name":"MUSC 061"},
  {"name":"HNU Chamber Ensemble","dept":"Music","short_name":"MUSC 062"},
  {"name":"HNU Orchestra","dept":"Music","short_name":"MUSC 063"},
  {"name":"Piano Ensemble","dept":"Music","short_name":"MUSC 064"},
  {"name":"Accompanying","dept":"Music","short_name":"MUSC 065"},
  {"name":"Perspectives in Music: History of Jazz","dept":"Music","short_name":"MUSC 071C"},
  {"name":"Medieval & Renaissance Music Theory & History","dept":"Music","short_name":"MUSC 094"},
  {"name":"Bytes&Notes:IntroComputerTechnology","dept":"Music","short_name":"MUSC 102"},
  {"name":"Classical Music II: Musicianship & Theory","dept":"Music","short_name":"MUSC 105AW"},
  {"name":"Classical Music II: History & Theory","dept":"Music","short_name":"MUSC 105BW"},
  {"name":"Music of the 20th and 21st Centuries:Musicianship and Theory","dept":"Music","short_name":"MUSC 108A"},
  {"name":"Music of the 20th and 21st Centuries: History and Theory","dept":"Music","short_name":"MUSC 108B"},
  {"name":"Private Lessons","dept":"Music","short_name":"MUSC 116"},
  {"name":"Private Lessons / Second Instrument","dept":"Music","short_name":"MUSC 117"},
  {"name":"Piano Class","dept":"Music","short_name":"MUSC 120B"},
  {"name":"Class Voice","dept":"Music","short_name":"MUSC 122B"},
  {"name":"Opera Scenes Workshop","dept":"Music","short_name":"MUSC 124"},
  {"name":"HNU Chorus","dept":"Music","short_name":"MUSC 160"},
  {"name":"HNU Chamber Singers","dept":"Music","short_name":"MUSC 161"},
  {"name":"HNU Chamber Ensemble","dept":"Music","short_name":"MUSC 162"},
  {"name":"HNU Orchestra","dept":"Music","short_name":"MUSC 163"},
  {"name":"Piano Ensemble","dept":"Music","short_name":"MUSC 164"},
  {"name":"Accompanying","dept":"Music","short_name":"MUSC 165"},
  {"name":"Perspectives in Music: History of Jazz","dept":"Music","short_name":"MUSC 171C"},
  {"name":"Choral Conducting","dept":"Music","short_name":"MUSC 181B"},
  {"name":"Recital","dept":"Music","short_name":"MUSC 190A"},
  {"name":"Recital","dept":"Music","short_name":"MUSC 190B"},
  {"name":"Fund of Nutrition","dept":"Nutrition","short_name":"NUTR 001"},
  {"name":"The Human Person","dept":"Philosophy","short_name":"PHIL 040W"},
  {"name":"The Human Person","dept":"Philosophy","short_name":"PHIL 040W"},
  {"name":"The Human Person","dept":"Philosophy","short_name":"PHIL 040W"},
  {"name":"The Human Person","dept":"Philosophy","short_name":"PHIL 140W"},
  {"name":"The Human Person","dept":"Philosophy","short_name":"PHIL 140W"},
  {"name":"The Human Person","dept":"Philosophy","short_name":"PHIL 140W"},
  {"name":"Ethics at Work","dept":"Philosophy","short_name":"PHIL 156"},
  {"name":"Tutorial: Theories of Knowledge","dept":"Philosophy","short_name":"PHIL 180A"},
  {"name":"StrnghtTrainingFitn","dept":"Physical Education","short_name":"PHED 010"},
  {"name":"StrnghtTrainingFitn","dept":"Physical Education","short_name":"PHED 010"},
  {"name":"StrnghtTrainingFitn","dept":"Physical Education","short_name":"PHED 010"},
  {"name":"Intercollegiate:Basketball-Men","dept":"Physical Education","short_name":"PHED 062"},
  {"name":"Intercollegiate:Basketball-Women","dept":"Physical Education","short_name":"PHED 062"},
  {"name":"Intercol: Volleyball - Men","dept":"Physical Education","short_name":"PHED 064"},
  {"name":"Intercol: Volleyball - Women","dept":"Physical Education","short_name":"PHED 064"},
  {"name":"Intrcol:CrossCountry - Men","dept":"Physical Education","short_name":"PHED 068"},
  {"name":"Intercol: Cross Country - Women","dept":"Physical Education","short_name":"PHED 068"},
  {"name":"Intercollegiate:Golf - Men","dept":"Physical Education","short_name":"PHED 070"},
  {"name":"Intcol:Soccer Men","dept":"Physical Education","short_name":"PHED 072"},
  {"name":"Intcol:Soccer Women","dept":"Physical Education","short_name":"PHED 072"},
  {"name":"Intercollegiate Softball","dept":"Physical Education","short_name":"PHED 074"},
  {"name":"Intercol Tennis- Women","dept":"Physical Education","short_name":"PHED 075"},
  {"name":"Intercol Baseball","dept":"Physical Education","short_name":"PHED 076"},
  {"name":"Special Topics: Yoga","dept":"Physical Education","short_name":"PHED 097"},
  {"name":"Special Topics: Hula","dept":"Physical Education","short_name":"PHED 097"},
  {"name":"Physical Education for Teachers","dept":"Physical Education","short_name":"PHED 110"},
  {"name":"Intercollegiate:Basketball-Men","dept":"Physical Education","short_name":"PHED 162"},
  {"name":"Intercollegiate:Basketball-Women","dept":"Physical Education","short_name":"PHED 162"},
  {"name":"Intercol: Volleyball- Men","dept":"Physical Education","short_name":"PHED 164"},
  {"name":"Intercol: Volleyball - Women","dept":"Physical Education","short_name":"PHED 164"},
  {"name":"Intrcol: CrossCountry- Men","dept":"Physical Education","short_name":"PHED 168"},
  {"name":"Intercol: Cross Country - Women","dept":"Physical Education","short_name":"PHED 168"},
  {"name":"Intercollegiate:Golf","dept":"Physical Education","short_name":"PHED 170"},
  {"name":"Intcol:Soccer Men","dept":"Physical Education","short_name":"PHED 172"},
  {"name":"Intcol:Soccer Women","dept":"Physical Education","short_name":"PHED 172"},
  {"name":"Intercollegiate Softball","dept":"Physical Education","short_name":"PHED 174"},
  {"name":"Intercol: Tennis - Women","dept":"Physical Education","short_name":"PHED 175"},
  {"name":"Intercol: Baseball","dept":"Physical Education","short_name":"PHED 176"},
  {"name":"Fundamentals Of Phys Science","dept":"Physical Science","short_name":"PHSC 015"},
  {"name":"General Physics II","dept":"Physics","short_name":"PHYS 008B"},
  {"name":"General Physics II Laboratory","dept":"Physics","short_name":"PHYS 008BL"},
  {"name":"Dynamics Of International Relations","dept":"Political Science","short_name":"PSCI 120"},
  {"name":"Internship","dept":"Political Science","short_name":"PSCI 196"},
  {"name":"Internship","dept":"Political Science","short_name":"PSCI 196 1"},
  {"name":"Internship","dept":"Political Science","short_name":"PSCI 196 2"},
  {"name":"Intro to Psychology","dept":"Psychology","short_name":"PSYC 001"},
  {"name":"Intro Psych Seminar:Psych Of Humor","dept":"Psychology","short_name":"PSYC 020"},
  {"name":"IntroLife-SpanDvlpmt","dept":"Psychology","short_name":"PSYC 030"},
  {"name":"Statistical Methods","dept":"Psychology","short_name":"PSYC 063"},
  {"name":"Experimental Psychology","dept":"Psychology","short_name":"PSYC 100W"},
  {"name":"Field Methods","dept":"Psychology","short_name":"PSYC 108W"},
  {"name":"Learning and Cognition","dept":"Psychology","short_name":"PSYC 120"},
  {"name":"Gender Issues","dept":"Psychology","short_name":"PSYC 147"},
  {"name":"Psychology of Personality","dept":"Psychology","short_name":"PSYC 160"},
  {"name":"Senior Seminar","dept":"Psychology","short_name":"PSYC 195W"},
  {"name":"Senior Seminar","dept":"Psychology","short_name":"PSYC 195W"},
  {"name":"Internship","dept":"Psychology","short_name":"PSYC 196"},
  {"name":"Internship","dept":"Psychology","short_name":"PSYC 196"},
  {"name":"Internship","dept":"Psychology","short_name":"PSYC 196 1"},
  {"name":"Internship","dept":"Psychology","short_name":"PSYC 196 1"},
  {"name":"Internship","dept":"Psychology","short_name":"PSYC 196 2"},
  {"name":"Internship","dept":"Psychology","short_name":"PSYC 196 2"},
  {"name":"Special Topics: Psychology of Humor","dept":"Psychology","short_name":"PSYC 197"},
  {"name":"Special Topics: Psychology Conventions","dept":"Psychology","short_name":"PSYC 197 1"},
  {"name":"Introduction to the New Testament","dept":"Religious Studies","short_name":"RLST 015"},
  {"name":"World Wisdom Traditions","dept":"Religious Studies","short_name":"RLST 075"},
  {"name":"Introduction to the New Testament","dept":"Religious Studies","short_name":"RLST 115"},
  {"name":"Spirituality and Social Justice","dept":"Religious Studies","short_name":"RLST 130A"},
  {"name":"World Wisdom Traditions","dept":"Religious Studies","short_name":"RLST 175"},
  {"name":"Religion in Mexico","dept":"Religious Studies","short_name":"RLST 177"},
  {"name":"Special Topics: Travel Course to Mexico","dept":"Religious Studies","short_name":"RLST 197 2"},
  {"name":"Intro to Sociology","dept":"Sociology","short_name":"SOCI 001"},
  {"name":"Statistical Methods","dept":"Sociology","short_name":"SOCI 063"},
  {"name":"Global Perspectives","dept":"Sociology","short_name":"SOCI 102W"},
  {"name":"Statistical Methods","dept":"Sociology","short_name":"SOCI 105"},
  {"name":"Field Methods","dept":"Sociology","short_name":"SOCI 108W"},
  {"name":"Gender Issues","dept":"Sociology","short_name":"SOCI 147"},
  {"name":"Racial & Ethnic Issues","dept":"Sociology","short_name":"SOCI 165"},
  {"name":"Latino/Hispanic Experience","dept":"Sociology","short_name":"SOCI 177"},
  {"name":"Internship","dept":"Sociology","short_name":"SOCI 196"},
  {"name":"Internship","dept":"Sociology","short_name":"SOCI 196 1"},
  {"name":"Internship","dept":"Sociology","short_name":"SOCI 196 2"},
  {"name":"Beginning Spanish II","dept":"Spanish Studies","short_name":"SPST 002"},
  {"name":"Intermediate Spanish II","dept":"Spanish Studies","short_name":"SPST 004"},
  {"name":"Advanced Spanish: Reading and Writing","dept":"Spanish Studies","short_name":"SPST 101W"},
  {"name":"AdvSpan:Listen&Speak","dept":"Spanish Studies","short_name":"SPST 102"},
  {"name":"Special Topics: Art of Today","dept":"Art","short_name":"ARTSA197"},
  {"name":"Principles of Biological Science","dept":"Biological Science","short_name":"BIOLA001A"},
  {"name":"Principles of Biological Science Lab","dept":"Biological Science","short_name":"BIOLA001AL"},
  {"name":"Human Physiology","dept":"Biological Science","short_name":"BIOLA011"},
  {"name":"Human Physiology Laboratory","dept":"Biological Science","short_name":"BIOLA011L"},
  {"name":"Human Anatomy","dept":"Biological Science","short_name":"BIOLA017"},
  {"name":"Human Anatomy Laboratory","dept":"Biological Science","short_name":"BIOLA017L"},
  {"name":"Allied Health Microbiology","dept":"Biological Science","short_name":"BIOLA020"},
  {"name":"Allied Health Microbiology Laboratory","dept":"Biological Science","short_name":"BIOLA020L"},
  {"name":"Principles of Accounting","dept":"Business","short_name":"BSADA011"},
  {"name":"Quantitative Analysis for Business","dept":"Business","short_name":"BSADA020"},
  {"name":"Decision Analysis for Business","dept":"Business","short_name":"BSADA105"},
  {"name":"Intro Chemistry for Health Science","dept":"Chemistry","short_name":"CHEMA007"},
  {"name":"Intro to Chemistry for Health Science Lab","dept":"Chemistry","short_name":"CHEMA007L"},
  {"name":"Essential Interpersonal Comm/Effect Speaking","dept":"Communications Studies","short_name":"COMMA001"},
  {"name":"Organizational Communication","dept":"Communications Studies","short_name":"COMMA101"},
  {"name":"Critical Reading & Writing I","dept":"English","short_name":"ENGLA001A"},
  {"name":"Critical Reading & Writing II","dept":"English","short_name":"ENGLA001B"},
  {"name":"Fiction","dept":"English","short_name":"ENGLA120"},
  {"name":"California History","dept":"History","short_name":"HISTA183"},
  {"name":"Premodern World","dept":"Integrative Studies Across Cultures","short_name":"ISACA102"},
  {"name":"Contemporary World","dept":"Integrative Studies Across Cultures","short_name":"ISACA104"},
  {"name":"Sr. Colloquium: \"Garbage\"","dept":"Integrative Studies Across Cultures","short_name":"ISACA195W"},
  {"name":"Fundamentals of Language","dept":"Linguistics","short_name":"LINGA145"},
  {"name":"Algebra 2 Workshop","dept":"Mathematics","short_name":"MATHA A"},
  {"name":"Algebra 2 Workshop","dept":"Mathematics","short_name":"MATHA A"},
  {"name":"Algebra I Workshop","dept":"Mathematics","short_name":"MATHA C"},
  {"name":"Refresher Mathematics Workshop","dept":"Mathematics","short_name":"MATHA R"},
  {"name":"The Human Person","dept":"Philosophy","short_name":"PHILA140W"},
  {"name":"Fund Of Phys Science","dept":"Physical Science","short_name":"PHSCA015"},
  {"name":"Introduction to Psychology","dept":"Psychology","short_name":"PSYCA001"},
  {"name":"Statistical Methods","dept":"Psychology","short_name":"PSYCA063"},
  {"name":"Counseling Theories","dept":"Psychology","short_name":"PSYCA167"},
  {"name":"Intor to Sociology","dept":"Sociology","short_name":"SOCIA001"},
  {"name":"Statistical Methods","dept":"Sociology","short_name":"SOCIA063"},
  {"name":"Statistical Methods","dept":"Sociology","short_name":"SOCIA105"},
  {"name":"Epidemiology","dept":"Biology","short_name":"BIOLA180"},
  {"name":"The Transition to Role of RN","dept":"Nursing","short_name":"NURSA001"},
  {"name":"Fundamentals of Nursing","dept":"Nursing","short_name":"NURSA009"},
  {"name":"Fundamentals of Nursing Lab","dept":"Nursing","short_name":"NURSA009L"},
  {"name":"Fundamentals of Nursing Lab","dept":"Nursing","short_name":"NURSA009L"},
  {"name":"Care of Adults","dept":"Nursing","short_name":"NURSA010"},
  {"name":"Care of Adults Clinical","dept":"Nursing","short_name":"NURSA010L"},
  {"name":"Care of Adults Clinical","dept":"Nursing","short_name":"NURSA010L"},
  {"name":"Care of Adults Clinical","dept":"Nursing","short_name":"NURSA010L"},
  {"name":"Care of the Mentally Ill","dept":"Nursing","short_name":"NURSA011"},
  {"name":"Care of the Mentally Ill Clinical","dept":"Nursing","short_name":"NURSA011L"},
  {"name":"Care of the Mentally Ill Clinical","dept":"Nursing","short_name":"NURSA011L"},
  {"name":"Health Assessment","dept":"Nursing","short_name":"NURSA031"},
  {"name":"Nursing Research","dept":"Nursing","short_name":"NURSA041"},
  {"name":"Maternal Health","dept":"Nursing","short_name":"NURSA120"},
  {"name":"Maternal Health Clinical","dept":"Nursing","short_name":"NURSA120L"},
  {"name":"Maternal Health Clinical","dept":"Nursing","short_name":"NURSA120L"},
  {"name":"Care of Children","dept":"Nursing","short_name":"NURSA130"},
  {"name":"Care of Children Clinical","dept":"Nursing","short_name":"NURSA130L"},
  {"name":"Care of Children Clinical","dept":"Nursing","short_name":"NURSA130L"},
  {"name":"Care of Children Clinical","dept":"Nursing","short_name":"NURSA130L"},
  {"name":"Care of Children Clinical","dept":"Nursing","short_name":"NURSA130L"},
  {"name":"Care of the Elderly","dept":"Nursing","short_name":"NURSA140"},
  {"name":"Care of the Elderly Clinical","dept":"Nursing","short_name":"NURSA140L"},
  {"name":"Care of the Elderly Clinical","dept":"Nursing","short_name":"NURSA140L"},
  {"name":"Community Health Nursing Clinical","dept":"Nursing","short_name":"NURSA142L"},
  {"name":"Family/Comm Health Nursing I Practicum","dept":"Nursing","short_name":"NURSA142L"},
  {"name":"Community Health Nursing","dept":"Nursing","short_name":"NURSA142W"},
  {"name":"Leardership & Management In Nursing","dept":"Nursing","short_name":"NURSA151"},
  {"name":"Leadership/Managemt Nursing Practicum","dept":"Nursing","short_name":"NURSA151L"},
  {"name":"Leadership/Managemt Nursing Practicum","dept":"Nursing","short_name":"NURSA151L"},
  {"name":"Evidence Based Nursing Practice","dept":"Nursing","short_name":"NURSA161"},
  {"name":"Senior Colloq \"The Search for Meaning in Modern Art and Lit\"","dept":"Integrative Studies Across Cultures","short_name":"ISACN195W"},
  {"name":"Health Assessment","dept":"Nursing","short_name":"NURSN131"},
  {"name":"Community Health Nursing Lab","dept":"Nursing","short_name":"NURSN142L"},
  {"name":"Community Health Nursing","dept":"Nursing","short_name":"NURSN142W"},
  {"name":"Senior Seminar","dept":"Nursing","short_name":"NURSN195W"},
  {"name":"World Wisdom Traditions","dept":"Religious Studies","short_name":"RLSTN175"},
  {"name":"Statistical Methods","dept":"Sociology","short_name":"SOCIN105"},
  {"name":"Sociology of Health Care & Health Policy","dept":"Sociology","short_name":"SOCIN156"},
  {"name":"Financial Management","dept":"Business","short_name":"BSAD 229"},
  {"name":"Substance Abuse Assessment and Treatment","dept":"Counseling Psychology","short_name":"CPSY 208"},
  {"name":"Assess, Diagnosis and Treatment of Victim","dept":"Counseling Psychology","short_name":"CPSY 209A"},
  {"name":"Assess, Diagnosis and Treatment of the Offender","dept":"Counseling Psychology","short_name":"CPSY 209B"},
  {"name":"ForensicPsycSeminar","dept":"Counseling Psychology","short_name":"CPSY 212"},
  {"name":"The Law and Professional Ethics","dept":"Counseling Psychology","short_name":"CPSY 215"},
  {"name":"Adv Issues in Correct & Comm Counseling","dept":"Counseling Psychology","short_name":"CPSY 226"},
  {"name":"Advanced Human Diversity Issues","dept":"Counseling Psychology","short_name":"CPSY 235"},
  {"name":"Alcohol & Chemical Dependency","dept":"Counseling Psychology","short_name":"CPSY 240A"},
  {"name":"Child Abuse Assessment and Reporting","dept":"Counseling Psychology","short_name":"CPSY 240B"},
  {"name":"Psychopharmacology","dept":"Counseling Psychology","short_name":"CPSY 245B"},
  {"name":"HIV/AIDS Assessment and Treatment","dept":"Counseling Psychology","short_name":"CPSY 245C"},
  {"name":"Treatment of Children","dept":"Counseling Psychology","short_name":"CPSY 260"},
  {"name":"Group Psychotherapy","dept":"Counseling Psychology","short_name":"CPSY 265"},
  {"name":"Group Psychotherapy","dept":"Counseling Psychology","short_name":"CPSY 265 2"},
  {"name":"Traumatology and Demographics","dept":"Counseling Psychology","short_name":"CPSY 273"},
  {"name":"Neurobiology of Trauma: Risk,Resiliency &PositivePsychology","dept":"Counseling Psychology","short_name":"CPSY 274"},
  {"name":"Psychological Assessment","dept":"Counseling Psychology","short_name":"CPSY 280 2"},
  {"name":"Intro to Supervised Practicum/Case Seminar","dept":"Counseling Psychology","short_name":"CPSY 285"},
  {"name":"Supervised Practicum and Case Seminar I","dept":"Counseling Psychology","short_name":"CPSY 290"},
  {"name":"Supervised Practicum and Case Seminar I","dept":"Counseling Psychology","short_name":"CPSY 290"},
  {"name":"Supervised Practicum and Case Seminar I","dept":"Counseling Psychology","short_name":"CPSY 295"},
  {"name":"Special Topics:Career Development Theories and Techniques","dept":"Counseling Psychology","short_name":"CPSY 297"},
  {"name":"Integrating Seminar","dept":"Counseling Psychology","short_name":"CPSY 298"},
  {"name":"Social Foundations in Education","dept":"Education","short_name":"EDUC 200"},
  {"name":"Educational Psychology","dept":"Education","short_name":"EDUC 201"},
  {"name":"Multicultural Education","dept":"Education","short_name":"EDUC 202B"},
  {"name":"Theories/Methods Second Language Acquisition","dept":"Education","short_name":"EDUC 203"},
  {"name":"Issues in Urban Education","dept":"Education","short_name":"EDUC 241"},
  {"name":"Behavior Management","dept":"Education","short_name":"EDUC 265"},
  {"name":"Practicum in Assessment","dept":"Education","short_name":"EDUC 266"},
  {"name":"Counseling/Collaboration Skills for Professionals","dept":"Education","short_name":"EDUC 267"},
  {"name":"Role of The Eductional Therapist","dept":"Education","short_name":"EDUC 268A"},
  {"name":"Technology for Students with MM Disabilities","dept":"Education","short_name":"EDUC 271"},
  {"name":"Educational Research","dept":"Education","short_name":"EDUC 290"},
  {"name":"Educational Evaluation","dept":"Education","short_name":"EDUC 292"},
  {"name":"Proposal Development","dept":"Education","short_name":"EDUC 293"},
  {"name":"Proposal Development","dept":"Education","short_name":"EDUC 293 2"},
  {"name":"Using Educational Research Tools","dept":"Education","short_name":"EDUC 296"},
  {"name":"Professional Academic Writing, Graduate Level","dept":"Education","short_name":"EDUC 297"},
  {"name":"Professional Academic Writing, Graduate Level","dept":"Education","short_name":"EDUC 297 2"},
  {"name":"Culminating Scholarly Activity","dept":"Education","short_name":"EDUC 298A"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298A"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298A"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298A"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298A"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298B"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298B"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298B"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298B"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298B"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298B"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298C"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298C"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298C"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298C"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298C"},
  {"name":"Masters Culminating Activity, in progress","dept":"Education","short_name":"EDUC 298C"},
  {"name":"Fiction","dept":"English","short_name":"ENGL 220"},
  {"name":"Fundamentals of Language","dept":"Linguistics","short_name":"LING 245"},
  {"name":"Private Lessons","dept":"Music","short_name":"MUSC 216"},
  {"name":"Opera Scenes Workshop","dept":"Music","short_name":"MUSC 224"},
  {"name":"Studies in Piano Literature","dept":"Music","short_name":"MUSC 226"},
  {"name":"Grad Sem in Musical Lit","dept":"Music","short_name":"MUSC 231"},
  {"name":"Folk Music","dept":"Music","short_name":"MUSC 243B"},
  {"name":"Solfege and Musicianship","dept":"Music","short_name":"MUSC 244B"},
  {"name":"Kodaly Pedagogy","dept":"Music","short_name":"MUSC 247B"},
  {"name":"Advanced Piano Pedagogy","dept":"Music","short_name":"MUSC 252"},
  {"name":"Advanced Vocal Pedagogy","dept":"Music","short_name":"MUSC 255"},
  {"name":"HNU Chamber Singers","dept":"Music","short_name":"MUSC 261"},
  {"name":"HNU Chamber Ensemble","dept":"Music","short_name":"MUSC 262"},
  {"name":"HNU Orchestra","dept":"Music","short_name":"MUSC 263"},
  {"name":"Advanced Piano Ensemble","dept":"Music","short_name":"MUSC 264"},
  {"name":"Advanced Accompanying","dept":"Music","short_name":"MUSC 265"},
  {"name":"Choral Conducting","dept":"Music","short_name":"MUSC 281B"},
  {"name":"Recital","dept":"Music","short_name":"MUSC 290A"},
  {"name":"Recital","dept":"Music","short_name":"MUSC 290B"},
  {"name":"Master's Project","dept":"Music","short_name":"MUSC 291A"},
  {"name":"Practicum","dept":"Music","short_name":"MUSC 296B"},
  {"name":"Practicum/Piano","dept":"Music","short_name":"MUSC 296D"},
  {"name":"Practicum/Vocal","dept":"Music","short_name":"MUSC 296F"},
  {"name":"Primary Care Thru Lifespan IV Lab","dept":"Nursing","short_name":"NURS 253L"},
  {"name":"Core Cs: Geo-Wisdom-Cosmol&Hum Spirit","dept":"Spirituality","short_name":"SPIR 201 4"},
  {"name":"Core Course: Weekend Component","dept":"Spirituality","short_name":"SPIR 204"},
  {"name":"Core Course Weekend Component","dept":"Spirituality","short_name":"SPIR 204 2"},
  {"name":"Public Forum","dept":"Spirituality","short_name":"SPIR 211B"},
  {"name":"Sophia Wisdom Circle","dept":"Spirituality","short_name":"SPIR 212"},
  {"name":"Sophia Praxis","dept":"Spirituality","short_name":"SPIR 213"},
  {"name":"Sophia Praxis","dept":"Spirituality","short_name":"SPIR 213 3"},
  {"name":"Visions of the Future","dept":"Spirituality","short_name":"SPIR 225"},
  {"name":"Mystics of Modern World","dept":"Spirituality","short_name":"SPIR 227"},
  {"name":"Archtypal Myth. DreamWork","dept":"Spirituality","short_name":"SPIR 265"},
  {"name":"Cosmology & the Human Spirit","dept":"Spirituality","short_name":"SPIR 290B"},
  {"name":"Spirit of Earth, Art, Spirit","dept":"Spirituality","short_name":"SPIR 291B"},
  {"name":"Master's Project","dept":"Spirituality","short_name":"SPIR 298"},
  {"name":"Primary Care I Lab","dept":"Nursing","short_name":"NURS 251AL"},
  {"name":"Primary Care II Lab","dept":"Nursing","short_name":"NURS 251BL"},
  {"name":"Primary Care Thru Lifespan III Lab","dept":"Nursing","short_name":"NURS 252L"},
  {"name":"Latino Culture","dept":"Education","short_name":"EDUC 305"},
  {"name":"Student Teaching Introduction: Single Subject","dept":"Education","short_name":"EDUC 320A"},
  {"name":"Student Teaching Practicum: Single Subject","dept":"Education","short_name":"EDUC 320B"},
  {"name":"Student Teaching in the Secondary School","dept":"Education","short_name":"EDUC 320C"},
  {"name":"Student Teaching in the Secondary School","dept":"Education","short_name":"EDUC 320C 10"},
  {"name":"Student Teaching in the Secondary School","dept":"Education","short_name":"EDUC 320C 9"},
  {"name":"Internship Teaching in a Secondary School","dept":"Education","short_name":"EDUC 320I"},
  {"name":"Internship Teaching","dept":"Education","short_name":"EDUC 320I 1"},
  {"name":"Internship Teaching in Secondary School","dept":"Education","short_name":"EDUC 320I 3"},
  {"name":"Internship Teaching in Secondary School","dept":"Education","short_name":"EDUC 320I 5"},
  {"name":"PACT 2 Support","dept":"Education","short_name":"EDUC 329"},
  {"name":"PACT 2 Support","dept":"Education","short_name":"EDUC 329"},
  {"name":"Student Teaching in the Elementary School","dept":"Education","short_name":"EDUC 330A"},
  {"name":"Internship Teaching: Multiple Subject","dept":"Education","short_name":"EDUC 330B"},
  {"name":"Student Teaching in the Elementary School","dept":"Education","short_name":"EDUC 330C"},
  {"name":"Internship Teaching:MultipleSubject","dept":"Education","short_name":"EDUC 330I"},
  {"name":"Internship Teaching, Multi-Subject","dept":"Education","short_name":"EDUC 330I 2"},
  {"name":"Internship Teaching, Multiple Subject","dept":"Education","short_name":"EDUC 330I 3"},
  {"name":"C & I Elementary School: Mathematics","dept":"Education","short_name":"EDUC 331"},
  {"name":"Curr/Instr Elementary School: Reading","dept":"Education","short_name":"EDUC 334"},
  {"name":"Curr/Instr Secondary School: Reading","dept":"Education","short_name":"EDUC 335"},
  {"name":"C&I Elementary Schools for Special Educ Teachers:Mathematics","dept":"Education","short_name":"EDUC 341"},
  {"name":"Field Studies Practicum, MM Disabilities","dept":"Education","short_name":"EDUC 361"},
  {"name":"Special Education Internship Teaching","dept":"Education","short_name":"EDUC 361I"},
  {"name":"Substance Abuse Assessment and Treatment","dept":"Counseling Psychology","short_name":"CPSY 408"},
  {"name":"Assess, Diagnosis and Treatment of Victim","dept":"Counseling Psychology","short_name":"CPSY 409A"},
  {"name":"Assess, Diagnosis and Treatment of the Offender","dept":"Counseling Psychology","short_name":"CPSY 409B"},
  {"name":"Forensic Psychology Prof. Prac Sem","dept":"Counseling Psychology","short_name":"CPSY 412"},
  {"name":"Adv Issues in Correct & Community Counseling","dept":"Counseling Psychology","short_name":"CPSY 426"},
  {"name":"Traumatology and Demographics","dept":"Counseling Psychology","short_name":"CPSY 473"},
  {"name":"Neurobiology of Trauma: Risk,Resiliency &PositivePsychology","dept":"Counseling Psychology","short_name":"CPSY 474"},
  {"name":"Intro to Supervised Practicum/Case Seminar","dept":"Counseling Psychology","short_name":"CPSY 485"},
  {"name":"Supervised Practicum and Case Seminar I","dept":"Counseling Psychology","short_name":"CPSY 490"},
  {"name":"Supervised Practicum and Case Seminar I","dept":"Counseling Psychology","short_name":"CPSY 490"},
  {"name":"Supervised Practicum & Case Seminar","dept":"Counseling Psychology","short_name":"CPSY 495"},
  {"name":"Social Foundations in Education","dept":"Education","short_name":"EDUC 400"},
  {"name":"Educational Psychology","dept":"Education","short_name":"EDUC 401"},
  {"name":"Multicultural Education","dept":"Education","short_name":"EDUC 402B"},
  {"name":"Curr/Instr Elementary School: Reading","dept":"Education","short_name":"EDUC 434"},
  {"name":"Neuropsychological Principles in Education","dept":"Education","short_name":"EDUC 459"},
  {"name":"Practicum for Educational Therapists","dept":"Education","short_name":"EDUC 460"},
  {"name":"Practicum in Assessment","dept":"Education","short_name":"EDUC 466"},
  {"name":"Counseling/Collaboration Skills for Professionals","dept":"Education","short_name":"EDUC 467"},
  {"name":"Role of the Educational Therapist","dept":"Education","short_name":"EDUC 468A"},
  {"name":"Technology for Students with MM Disabilities","dept":"Education","short_name":"EDUC 471"},
  {"name":"Primary Care I Lab","dept":"Nursing","short_name":"NURS 451AL"},
  {"name":"Primary Care II Lab","dept":"Nursing","short_name":"NURS 451BL"},
  {"name":"Primary Care Thru Lifespan III","dept":"Nursing","short_name":"NURS 452L"},
  {"name":"Primary Care Thru Lifespan IV Lab","dept":"Nursing","short_name":"NURS 453L"},
  {"name":"Core Cs: Geo-Wisdom-Cosmol/Hum Spirit","dept":"Spirituality","short_name":"SPIR 401"},
  {"name":"Core Course Weekend Component","dept":"Spirituality","short_name":"SPIR 404"},
  {"name":"Core Course Weekend Component","dept":"Spirituality","short_name":"SPIR 404 2"},
  {"name":"Public Forum","dept":"Spirituality","short_name":"SPIR 411B"},
  {"name":"Sophia Wisdom Circle","dept":"Spirituality","short_name":"SPIR 412"},
  {"name":"Sophia Praxis","dept":"Spirituality","short_name":"SPIR 413"},
  {"name":"Sophia Praxis","dept":"Spirituality","short_name":"SPIR 413 3"},
  {"name":"Visions of the Future","dept":"Spirituality","short_name":"SPIR 425"},
  {"name":"Mystics of Modern World","dept":"Spirituality","short_name":"SPIR 427"},
  {"name":"Archetypal Mythology in Dreamwork","dept":"Spirituality","short_name":"SPIR 465"},
  {"name":"Cosmology & the Human Spirit","dept":"Spirituality","short_name":"SPIR 490B"},
  {"name":"Spirit of Earth, Art & Spirit, Weekends","dept":"Spirituality","short_name":"SPIR 491B"},
  {"name":"Independent Study: Visions","dept":"Spirituality","short_name":"SPIR 499 1"},
  {"name":"Principles of Accounting","dept":"Business","short_name":"BSADA010"},
  {"name":"Business Management","dept":"Business","short_name":"BSADA130"},
  {"name":"Human Resource Management","dept":"Business","short_name":"BSADA145"},
  {"name":"Consumer Behavior","dept":"Business","short_name":"BSADA161"},
  {"name":"Professional Writing","dept":"Communications Studies","short_name":"COMMA108W"},
  {"name":"Principles of Economics (Macro)","dept":"Economics","short_name":"ECONA001"},
  {"name":"Principles of Economics (Micro)","dept":"Economics","short_name":"ECONA002"},
  {"name":"Statistical Methods","dept":"Economics","short_name":"ECONA015"},
  {"name":"Professional Writing","dept":"English","short_name":"ENGLA108W"},
  {"name":"Adult Development and Aging","dept":"Psychology","short_name":"PSYCA131"},
  {"name":"Religion, Philiosophy, and Human Rights","dept":"Religious Studies","short_name":"RLSTA122"},
  {"name":"Advanced Management: Leading Change","dept":"Business","short_name":"BSAD 230"},
  {"name":"Investments","dept":"Business","short_name":"BSAD 237"},
  {"name":"Environmental Economics","dept":"Business","short_name":"BSAD 241"},
  {"name":"Leadership Development","dept":"Business","short_name":"BSAD 250"},
  {"name":"Diverse Consumer Behavior","dept":"Business","short_name":"BSAD 261"},
  {"name":"History of Composition and Rhetoric","dept":"English","short_name":"ENGL 203A"},
  {"name":"Primary Care Thru Lifespan IV Lab","dept":"Nursing","short_name":"NURS 253L"},
  {"name":"Tai Chi","dept":"Spirituality","short_name":"SPIR 254"},
  {"name":"Special Topics: Embodying Ecological Action and Vision","dept":"Spirituality","short_name":"SPIR 297"},
  {"name":"Health Promotion","dept":"Nursing","short_name":"NURS 214"},
  {"name":"Health Economics & Organization Des","dept":"Nursing","short_name":"NURS 216"},
  {"name":"Health Economics & Organization Des","dept":"Nursing","short_name":"NURS 216"},
  {"name":"Scientific Inquiry","dept":"Nursing","short_name":"NURS 217A"},
  {"name":"Scientific Inquiry","dept":"Nursing","short_name":"NURS 217A"},
  {"name":"Management & Development","dept":"Nursing","short_name":"NURS 220"},
  {"name":"Managing Health Care Delivery","dept":"Nursing","short_name":"NURS 234B"},
  {"name":"Advanced Health Assessment","dept":"Nursing","short_name":"NURS 240"},
  {"name":"Advanced Health Assessment","dept":"Nursing","short_name":"NURS 240"},
  {"name":"Advanced Health Assessment Lab","dept":"Nursing","short_name":"NURS 240L"},
  {"name":"Advanced Health Assessment Lab","dept":"Nursing","short_name":"NURS 240L"},
  {"name":"Advanced Health Assessment Lab","dept":"Nursing","short_name":"NURS 240L"},
  {"name":"Advanced Health Assessment Lab","dept":"Nursing","short_name":"NURS 240L"},
  {"name":"Primary Care I Lab","dept":"Nursing","short_name":"NURS 251AL"},
  {"name":"Primary Care II Lab","dept":"Nursing","short_name":"NURS 251BL"},
  {"name":"Primary Care Thru Lifespan III","dept":"Nursing","short_name":"NURS 252"},
  {"name":"Primary Care Thru Lifespan III Lab","dept":"Nursing","short_name":"NURS 252L"},
  {"name":"Clinical Faculty Practicum I","dept":"Nursing","short_name":"NURS 265A"},
  {"name":"Using Computers in the K-12 Classroom, Level 1","dept":"Education","short_name":"EDUC 353B"},
  {"name":"Consultation and Colllaboration for Students with ASD","dept":"Education","short_name":"EDUC 359"},
  {"name":"Hlth Promo/Risk Reduc of Diverse Pop","dept":"Nursing","short_name":"NURS 414"},
  {"name":"Concept/Theor Nursing Admin/Manage","dept":"Nursing","short_name":"NURS 420"},
  {"name":"Man Hlthcare Del/Div Pop/Comm Env I","dept":"Nursing","short_name":"NURS 434B"},
  {"name":"Advanced Health Assessment","dept":"Nursing","short_name":"NURS 440"},
  {"name":"Advanced Heath Assessment Lab","dept":"Nursing","short_name":"NURS 440L"},
  {"name":"Primary Care I Lab","dept":"Nursing","short_name":"NURS 451AL"},
  {"name":"Primary Care II Lab","dept":"Nursing","short_name":"NURS 451BL"},
  {"name":"Primary Care Family through Lifespan III","dept":"Nursing","short_name":"NURS 452"},
  {"name":"Primary Care Thru Lifespan III","dept":"Nursing","short_name":"NURS 452L"},
  {"name":"Primary Care Thru Lifespan IV Lab","dept":"Nursing","short_name":"NURS 453L"},
  {"name":"Clinical Faculty Practicum I","dept":"Nursing","short_name":"NURS 465A"},
  {"name":"Tai Chi","dept":"Spirituality","short_name":"SPIR 454"},
  {"name":"Special Topics: Embodying Ecological Action and Vision","dept":"Spirituality","short_name":"SPIR 497"},
  {"name":"Internship","dept":"Business","short_name":"BSAD 196 1"},
  {"name":"Principles of Accounting","dept":"Business","short_name":"BSADA011"},
  {"name":"Business Law","dept":"Business","short_name":"BSADA018"},
  {"name":"Marketing Research","dept":"Business","short_name":"BSADA165"},
  {"name":"Strategic Management","dept":"Business","short_name":"BSADA195W"},
  {"name":"Professional Writing","dept":"Communications Studies","short_name":"COMMA108W"},
  {"name":"Communication Internships","dept":"Communications Studies","short_name":"COMMA196"},
  {"name":"Communication Internships","dept":"Communications Studies","short_name":"COMMA196 1"},
  {"name":"Internship","dept":"Communications Studies","short_name":"COMMA196 2"},
  {"name":"Spreadsheets","dept":"Computer Systems","short_name":"CSCIA010C"},
  {"name":"Professional Writing","dept":"English","short_name":"ENGLA108W"},
  {"name":"Poetry","dept":"English","short_name":"ENGLA121"},
  {"name":"City:Culture, History, & Power","dept":"History","short_name":"HISTA126"},
  {"name":"Ethics: The Problem of Friendship","dept":"Philosophy","short_name":"PHILA151"},
  {"name":"World Wisdom Traditions","dept":"Religious Studies","short_name":"RLSTA175"},
  {"name":"City:Culture, History, & Power","dept":"Sociology","short_name":"SOCIA160"},
  {"name":"Public Finance and Management","dept":"Business","short_name":"BSAD 243"},
  {"name":"Building Learning Organizations","dept":"Business","short_name":"BSAD 253"},
  {"name":"Marketing Management","dept":"Business","short_name":"BSAD 260"},
  {"name":"The Global Imperative: Strategic Marketing","dept":"Business","short_name":"BSAD 263"},
  {"name":"Marketing Research","dept":"Business","short_name":"BSAD 265"},
  {"name":"Strategy in Global Environment","dept":"Business","short_name":"BSAD 295"},
  {"name":"Community Mental Health C","dept":"Counseling Psychology","short_name":"CPSY 293"},
  {"name":"Role of The Eductional Therapist","dept":"Education","short_name":"EDUC 268B"},
  {"name":"Poetry","dept":"English","short_name":"ENGL 221"},
  {"name":"Final Project","dept":"English","short_name":"ENGL 298"},
  {"name":"Primary Care Thru Lifespan IV Lab","dept":"Nursing","short_name":"NURS 253L"},
  {"name":"Paint. As Spont. Expression","dept":"Spirituality","short_name":"SPIR 243"},
  {"name":"Indigenous Wisdom Anc. Stories","dept":"Spirituality","short_name":"SPIR 262A"},
  {"name":"Capstone","dept":"Nursing","short_name":"NURS 217B"},
  {"name":"Finance & Budgeting in Health Care","dept":"Nursing","short_name":"NURS 223"},
  {"name":"Human Resource Management & Develop","dept":"Nursing","short_name":"NURS 224"},
  {"name":"Prov Ldrsgip/Hlth Del/Div Pop/Comm II","dept":"Nursing","short_name":"NURS 235"},
  {"name":"Primary Care Family Thru Lifespan I","dept":"Nursing","short_name":"NURS 241"},
  {"name":"Advanced Pharmacology","dept":"Nursing","short_name":"NURS 244"},
  {"name":"Primary Care I","dept":"Nursing","short_name":"NURS 251A"},
  {"name":"Primary Care I Lab","dept":"Nursing","short_name":"NURS 251AL"},
  {"name":"Primary Care II Lab","dept":"Nursing","short_name":"NURS 251BL"},
  {"name":"Primary Care Thru Lifespan III Lab","dept":"Nursing","short_name":"NURS 252L"},
  {"name":"Pri Care Thru Lifespan III","dept":"Nursing","short_name":"NURS 253"},
  {"name":"Theories Of Nursing","dept":"Nursing","short_name":"NURS 261"},
  {"name":"Teaching Strategies","dept":"Nursing","short_name":"NURS 262"},
  {"name":"Clinical Faculty Pract II","dept":"Nursing","short_name":"NURS 265B"},
  {"name":"US: Constitution Prep","dept":"Education","short_name":"EDUC 375"},
  {"name":"Health Education for Teachers","dept":"Education","short_name":"EDUC 393A"},
  {"name":"Role of the Educational Therapist","dept":"Education","short_name":"EDUC 468B"},
  {"name":"Finance and Budgeting in Healthcare","dept":"Nursing","short_name":"NURS 423"},
  {"name":"Human Resource Manage/Develop","dept":"Nursing","short_name":"NURS 424"},
  {"name":"Prov Ldrship/Hlth Dev/Div Pop/Comm II","dept":"Nursing","short_name":"NURS 435"},
  {"name":"Primary Care Family Thru Lifespan I","dept":"Nursing","short_name":"NURS 441"},
  {"name":"Advanced Pharmacology","dept":"Nursing","short_name":"NURS 444"},
  {"name":"Primary Care Family/life:Role Perf I","dept":"Nursing","short_name":"NURS 451A"},
  {"name":"Primary Care I Lab","dept":"Nursing","short_name":"NURS 451AL"},
  {"name":"Primary Care II Lab","dept":"Nursing","short_name":"NURS 451BL"},
  {"name":"Primary Care Thru Lifespan III","dept":"Nursing","short_name":"NURS 452L"},
  {"name":"Primary Care Thru Lifespan IV","dept":"Nursing","short_name":"NURS 453"},
  {"name":"Primary Care Thru Lifespan IV Lab","dept":"Nursing","short_name":"NURS 453L"},
  {"name":"Concepts & Theories","dept":"Nursing","short_name":"NURS 461"},
  {"name":"Teaching Strategies","dept":"Nursing","short_name":"NURS 462"},
  {"name":"Clinical Faculty Practicum II","dept":"Nursing","short_name":"NURS 465B"},
  {"name":"Painting as Spontaneous Expression","dept":"Spirituality","short_name":"SPIR 443"},
  {"name":"IndigenousWisdomThruAncestralStories","dept":"Spirituality","short_name":"SPIR 462A"},
]
